package com.khany.orchsagapilot.config;

public enum SagaStates {
    ORDER_REQUEST,
    DISCOUNT_QUERYING,
    DISCOUNT_QUERY_OK,
    DISCOUNT_QUERY_FAIL,
    POINT_QUERYING,
    POINT_QUERY_OK,
    POINT_QUERY_FAIL,
    DISCOUNT_REQUESTING,
    DISCOUNT_REQUEST_OK,
    DISCOUNT_REQUEST_FAIL,
    PAYMENT_REQUESTING,
    PAYMENT_REQUEST_OK,
    PAYMENT_REQUEST_FAIL,
    ORDER_CANCEL_REQUESTING,
    PAYMENT_CANCELING,
    DISCOUNT_CANCELING,
    ORDER_CANCELING,
    ORDER_COMPLETING
}
