package com.khany.orchsagapilot.config;

public enum SagaStates {
    ORDER_REQUEST,
    DISCOUNT_CHECKED,
    DISCOUNT_CHECK_OK,
    DISCOUNT_CHECK_FAIL,
    POINT_CHECKED,
    POINT_CHECK_OK,
    POINT_CHECK_FAIL,
    DISCOUNT_REQUESTED,
    DISCOUNT_REQUEST_OK,
    DISCOUNT_REQUEST_FAIL,
    PAYMENT_REQUESTED,
    PAYMENT_REQUEST_OK,
    PAYMENT_REQUEST_FAIL,
    ORDER_CANCEL_REQUEST,
    PAYMENT_CANCEL_REQUEST,
    DISCOUNT_CANCEL_REQUEST,
    ORDER_CANCELED,
    ORDER_COMPLETED
}
